# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v0.1
        required: false

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Run Spigot Action
      uses: SpraxDev/Action-SpigotMC@v3
      with:
        # A comma-separated list of Spigot version that should be compiled
        # These values are later given to the BuildTools.jar as '--rev' argument
        #
        # Example: latest, 1.14.4, 1.8.8
        versions: 1.18 # Optional

        # Should sources be generated?
        # If enabled, BuildTools is provided the '--generate-source' argument
        generateSrc: false # Optional

        # Should the documentation be generated?
        # If enabled, BuildTools is provided the '--generate-docs' argument
        generateDoc: false # Optional

        # Should we disable the BuildTools's Java-Version-Check?
        # If enabled, BuildTools is provided the '--disable-java-check' argument
        disableJavaCheck: false # Optional

        # Disables the check for existing files in the local maven repository
        # Normally, a version is skipped if it is already installed
        # in the local maven repository to speed up build time
        forceRun: false # Optional

        # The amount of builds allowed to run at the same time
        # Set to '-1' to use system's cpu core count
        threads: -1 # Optional

        # You can choose between different BuildTools to be used by this action
        # ~~'SpraxDev' is my fork of SpigotMC's that introduces some changes (https://github.com/SpraxDev/Spigot-BuildTools/#breaking-changes)~~
        # My (SpraxDev) provider is causing some builds to fail depending on the build environment
        # Available: SpraxDev, SpigotMC
        buildToolProvider: SpigotMC # Optional
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false