# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI/CD Java8

on: 
  push:
    branches:
      - master  
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v0.1
        required: false

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Run Spigot Action
      uses: SpraxDev/Action-SpigotMC@v3
      with:
        # A comma-separated list of Spigot version that should be compiled
        # These values are later given to the BuildTools.jar as '--rev' argument
        #
        # Example: latest, 1.14.4, 1.8.8
        versions: 1.12.2 # Optional

        # Should sources be generated?
        # If enabled, BuildTools is provided the '--generate-source' argument
        generateSrc: false # Optional

        # Should the documentation be generated?
        # If enabled, BuildTools is provided the '--generate-docs' argument
        generateDoc: false # Optional

        # Should we disable the BuildTools's Java-Version-Check?
        # If enabled, BuildTools is provided the '--disable-java-check' argument
        disableJavaCheck: false # Optional

        # Disables the check for existing files in the local maven repository
        # Normally, a version is skipped if it is already installed
        # in the local maven repository to speed up build time
        forceRun: false # Optional

        # The amount of builds allowed to run at the same time
        # Set to '-1' to use system's cpu core count
        threads: -1 # Optional

        # You can choose between different BuildTools to be used by this action
        # ~~'SpraxDev' is my fork of SpigotMC's that introduces some changes (https://github.com/SpraxDev/Spigot-BuildTools/#breaking-changes)~~
        # My (SpraxDev) provider is causing some builds to fail depending on the build environment
        # Available: SpraxDev, SpigotMC
        buildToolProvider: SpigotMC # Optional
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Get Short Commit Hash
      id: commit_hash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Get plugin version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: plugin_version      
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::Inventories_${{ steps.plugin_version.outputs.version }}_${{ steps.commit_hash.outputs.sha_short }}_java8"
    - name: Create Release
      uses: softprops/action-gh-release@v1      
      with:
        files: ./target/inventories-1.0-SNAPSHOT.jar
        tag_name: ${{ steps.tag.outputs.release_tag }}
        token: ${{ secrets.GH_TOKEN }}
        
